### PR TITLE
Added support for (de)serializing DateTime properties 'created' &  's…

### PR DESCRIPTION
**Pull request by Tjeerd**
Added support for (de)serializing DateTime properties 'created' & 'stored' of a Statement.

### CODE REVIEW

**Comment by Tjeerd** [comment]
Failing build because of missing DateTimeNormalizer, this Normalizer is introduced in Symfony/Serializer  3.1.

**Comment by xabbuh** [comment]
@Tjeerd Thank you for this nice pull request. Can you switch the implementation to create `\DateTime` instances directly instead of using the new `DateTimeNormalizer`? The implementation should be straight-forward as the code of that normalizer isn't too complicated (you can borrow some code from the Symfony implementation). And can you then also introduce a new test for this?

**Comment by xabbuh** [comment]
Thank you @Tjeerd for spotting the issue and for creating this pull request. I have taken your commit and finished it in #10 (adding a test and a custom normalizer for older releases of the Symfony Serializer component). It is now included in the `0.2.2` release.

**Comment by Tjeerd** [comment]
Hi, yeah great, thanks! Sorry for not getting back to you, I was occupied with some other work. I have some more PR's coming... :wink:

**Comment by xabbuh** [comment]
@Tjeerd Don't worry about that. :) By the way, just to let you know: I am currently working on improvements for the xAPI related packages. So before putting effort into creating pull request I suggest to create an issue first to not waste your time in case you do something I am already working on. :)

**Pull request closed without merging**
