### PR TITLE
Introduce a new PersonSerializerInterface

### PR DESCRIPTION
**Pull request by Lctrs**
Spec for this are here : https://github.com/adlnet/xAPI-Spec/blob/master/xAPI-Communication.md#agentsres

Another possibility is to introduce a `Person` class in the model then a `PersonSerializerInterface` into this repo.

WDYT @xabbuh ?

### CODE REVIEW

**Comment by Lctrs** [comment]
If we go with the solution proposed in this PR, we'll have to play with the `$context` parameter in the Symfony's Serializer implementation to serialize an array of agents into a Person.

Introducing a `Person` class in the model will certainly make it easier to implement in the serializer implementation.

**Comment by xabbuh** [comment]
I am 👍 for adding a `Person` class to the model package.

**Comment by Lctrs** [comment]
See php-xapi/model#60

**Comment by xabbuh** [comment]
@Lctrs I am deeply sorry for the recent delays. :( I have now merged php-xapi/model#60. You can now rebase here. :)

**Comment by Lctrs** [comment]
No problem. I understand that you've been really busy with the last release of Symfony.

On my side, I have internally forked your libraries, united them in one Symfony app and continued to work on this. I have an implementation that pass ~1200 tests of the LRS conformance suite from ADL. 

I'll work on PRs in the next weeks to sync my work with your libraries. I don't have access right now to my code as it's a public holiday today in France.

**Comment by Lctrs** [comment]
@xabbuh Done.

**Comment by xabbuh** [comment]
Thank you @Lctrs.

**Pull request merged**
